modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="xcruell, YesMenn!"
description='''
Bridges Veil shader rendering through Iris shaderpacks. Veil shaders are merged
into the active shaderpack's gbuffer and shadow programs at runtime.
'''

[[mixins]]
config="${mod_id}.mixins.iris.json"

[[mixins]]
config="${mod_id}.mixins.veil.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="iris"
    type="required"
    versionRange="[1.8.1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="veil"
    type="required"
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="CLIENT"
